"""Generate the paper's data figures (figs 2-5) from the pinned results JSONs.

Outputs paper/latex/figures/fig{1..5}_*.pdf plus 300-DPI PNG twins.
Grayscale-safe: gray levels + distinct markers/line styles only.
IEEE geometry: 3.5 in single column, 7.16 in double column.
"""
import json
import os

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIGDIR = os.path.join(ROOT, "paper", "latex", "figures")
SUPPDIR = os.path.join(ROOT, "paper", "supplementary")
os.makedirs(FIGDIR, exist_ok=True)
os.makedirs(SUPPDIR, exist_ok=True)

plt.rcParams.update({"font.family": "serif", "font.size": 8,
  "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.5,
  "axes.spines.top": False, "axes.spines.right": False,
  "legend.frameon": False})
plt.rcParams["pdf.fonttype"] = 42  # IEEE font embedding

COLORS = {"DGFed": "#0072B2", "DGFed-P": "#D55E00",
          "FedAvg": "#009E73", "FedProx": "#CC79A7",
          "No compression": "#7F7F7F"}
MARKERS = {"DGFed": "o", "DGFed-P": "s", "FedAvg": "^",
           "FedProx": "v", "No compression": "D"}


def J(rel):
    return json.load(open(os.path.join(ROOT, rel)))


def save(fig, name, out=None):
    for ext, kw in (("pdf", {}), ("png", {"dpi": 300})):
        fig.savefig(os.path.join(out or FIGDIR, f"{name}.{ext}"), bbox_inches="tight", **kw)
    plt.close(fig)
    print(f"[saved] {name}.pdf/.png")


# fig 1 (control-loop schematic) is generated by the standalone
# fig1_redraw.py next to this script — the single source of truth for it.


# --------------------------------------------- fig 2: communication–accuracy
def fig2():
    fig, axes = plt.subplots(2, 1, figsize=(3.5, 4.0), sharex=True)
    for ax, part in zip(axes, ["unit", "regime"]):
        cal = J(f"results/merged5/FD004_calibrated/ablation_{part}.json")
        reb = J(f"results/merged5/FD004_rebased/ablation_{part}.json")
        pts = []
        for label, key, src in [
            ("Proposed", "DGFed", cal["no_personal_head"]),
            ("DGFed-P (pers. head)", "DGFed-P", cal["full"]),
            ("Proposed, no compr.", "No compression", reb["proposed_no_compression"]),
        ]:
            pts.append((label, key, src["total_MB_uploaded_mean"],
                        src["rmse_mean"], src["rmse_std"]))
        for label, key, m in [("FedAvg", "FedAvg", "fedavg"),
                              ("FedProx", "FedProx", "fedprox")]:
            runs = J(f"results/merged5/FD004_{part}/{m}_FD004.json")["runs"]
            r = [x["rmse"] for x in runs]
            pts.append((label, key, np.mean([x["total_MB_uploaded"] for x in runs]),
                        np.mean(r), np.std(r)))
        for label, key, mb, rm, sd in pts:
            ax.errorbar(mb, rm, yerr=sd, marker=MARKERS[key], ms=5,
                        color=COLORS[key], capsize=2, lw=0.8, ls="none",
                        label=label)
        cen = [x["rmse"] for x in J(f"results/merged5/FD004_{part}/central_FD004.json")["runs"]]
        ax.axhline(np.mean(cen), color="#444444", lw=0.8, ls=":")
        loc = np.mean([x["rmse"] for x in J(f"results/merged5/FD004_{part}/local_FD004.json")["runs"]])
        ax.axhline(loc, color="#999999", lw=0.8, ls="--")
        tx = 0.03 if part == "unit" else 0.45
        ax.text(tx, np.mean(cen), "centralized", fontsize=6, va="bottom",
                ha="left", transform=ax.get_yaxis_transform(), color="#444444")
        ax.text(tx, loc, "local-only", fontsize=6, va="bottom",
                ha="left", transform=ax.get_yaxis_transform(), color="#999999")
        ax.set_xscale("log")
        ax.set_ylabel("RMSE (cycles)")
        ax.set_title(f"FD004, {part} partition "
                     f"({cal['full']['n_clients']} clients)", fontsize=7.5)
    axes[0].legend(loc="center left", frameon=False, handletextpad=0.3)
    axes[1].set_xlabel("Total upload (MB, log scale)")
    fig.tight_layout(h_pad=1.0)
    save(fig, "fig2_comm_accuracy")


# ------------------------------------------------- fig 3: paired seed deltas
def fig3():
    an = J("results/merged5/analysis_paired_seed_FD004.json")["partitions"]
    arms = ["+personal_head", "proposed_no_drift_signal", "proposed_no_event_trigger",
            "proposed_plain_aggregation", "proposed_no_compression"]
    labels = ["+ personal head", "– drift signal", "– event trigger",
              "– drift/stale agg.", "– compression"]
    arm_key = {"+personal_head": "DGFed-P",
               "proposed_no_drift_signal": "DGFed",
               "proposed_no_event_trigger": "DGFed",
               "proposed_plain_aggregation": "DGFed",
               "proposed_no_compression": "No compression"}
    fig, axes = plt.subplots(1, 2, figsize=(3.5, 2.45), sharey=True)
    for ax, part in zip(axes, ["unit", "regime"]):
        for i, arm in enumerate(arms):
            d = an[part][arm]["per_seed_delta"]
            y = len(arms) - 1 - i
            k = arm_key[arm]
            ax.plot(d, [y] * len(d), MARKERS[k], ms=3, mfc="none",
                    mec=COLORS[k], mew=0.8)
            ax.plot(np.mean(d), y, MARKERS[k], ms=5, color=COLORS[k])
        ax.axvline(0, color="#444444", lw=0.7)
        ax.set_yticks(range(len(arms)))
        ax.set_yticklabels(labels[::-1])
        ax.set_title(part, fontsize=7.5)
        ax.grid(axis="x")
        ax.set_xlabel(r"$\Delta$RMSE vs. proposed")
    fig.tight_layout(w_pad=0.6)
    save(fig, "fig3_paired_deltas", out=SUPPDIR)


# ---------------------------------------------------------- fig 4: retention
def fig4():
    fig, axes = plt.subplots(1, 2, figsize=(3.5, 1.75), sharey=True)
    for ax, part in zip(axes, ["unit", "regime"]):
        cal = J(f"results/merged5/FD004_calibrated/ablation_{part}.json")
        for src, label, key, ls in [
            (cal["no_personal_head"], "Proposed", "DGFed", "-"),
            (cal["full"], "DGFed-P", "DGFed-P", "--"),
        ]:
            bins = np.array(src["retention_rmse_bins"], dtype=float)
            m, s = bins.mean(axis=0), bins.std(axis=0)
            x = np.arange(1, bins.shape[1] + 1)
            ax.plot(x, m, ls=ls, marker=MARKERS[key], ms=3,
                    color=COLORS[key], label=label)
            ax.fill_between(x, m - s, m + s, color=COLORS[key],
                            alpha=0.18, lw=0)
        ax.set_xticks(x)
        ax.set_xlabel("ordered test-tail bin")
        ax.set_title(part, fontsize=7.5)
    axes[0].set_ylabel("RMSE (cycles)")
    axes[0].legend(frameon=False, loc="lower left", handlelength=1.6)
    fig.tight_layout(w_pad=0.6)
    save(fig, "fig4_retention")


# ------------------------------------------------------- fig 5: lambda sweep
def fig5():
    sw = J("results/ph_sweep_FD004_unit.json")
    lams = sorted(float(k) for k in sw)
    fire = [sw[f"{l:g}"]["drift_fire_rate"] * 100 for l in lams]
    rmse = [sw[f"{l:g}"]["rmse"] for l in lams]
    fig, ax = plt.subplots(figsize=(3.5, 2.0))
    ax.axhspan(3, 8, color="0.9", lw=0)
    ax.text(260, 5.4, "target band", fontsize=6.5, color="0.35", va="center")
    ax.plot(lams, fire, "-o", ms=4, color=COLORS["DGFed"], label="drift fire rate")
    ax.axvline(5000, color="0.0", lw=0.7, ls=":")
    # observed transfer points at the chosen lambda (portability limitation)
    for y, lbl, dy in [(19.0, "FD004-regime", 0.6), (14.3, "FD002-regime", 0.6),
                       (6.7, "FD002-unit", -1.9)]:
        ax.plot(5000, y, "o", ms=4, mfc="1.0", mec=COLORS["DGFed"], mew=0.9)
        ax.annotate(lbl, (5000, y), xytext=(3550, y + dy), fontsize=5.5,
                    ha="right", color="0.25",
                    arrowprops=dict(arrowstyle="-", lw=0.5, color="0.55"))
    ax.text(4500, 13.5, "chosen $\\lambda$", fontsize=6.5, ha="right",
            rotation=90, va="bottom", color="0.25")
    ax.set_xscale("log")
    ax.set_xticks(lams)
    ax.set_xticklabels([f"{int(l)}" for l in lams])
    ax.minorticks_off()
    ax.set_xlabel(r"Page–Hinkley threshold $\lambda$")
    ax.set_ylabel("drift fire rate (%)")
    ax2 = ax.twinx()
    ax2.spines["right"].set_visible(True)
    ax2.grid(False)
    ax2.plot(lams, rmse, "--s", ms=3.5, color="#7F7F7F", label="RMSE (50 rounds)")
    ax2.set_ylabel("RMSE (cycles)", color="0.35")
    ax2.tick_params(axis="y", labelcolor="0.35")
    ax2.minorticks_off()
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, frameon=False, ncols=2,
              loc="lower center", bbox_to_anchor=(0.5, 1.0))
    ax.grid(True, which="major", lw=0.3, color="0.9")
    fig.tight_layout()
    save(fig, "fig5_lambda_sweep", out=SUPPDIR)


if __name__ == "__main__":
    fig2(); fig3(); fig4(); fig5()  # fig1: run fig1_redraw.py
